name: Send Telegram Message

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
 
jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
  
      - name: Run Python script
        run: |
          python main.py
